name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore MotoFleetManagement.sln

      - name: Build solution
        run: dotnet build MotoFleetManagement.sln --no-restore --configuration Release

      - name: Run all tests with coverage
        run: |
          dotnet test MotoFleetManagement.sln --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Report coverage
        uses: dorny/paths-filter@v3

      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: ./TestResults
