name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore MotoFleetManagement.sln

      - name: Build solution
        run: dotnet build MotoFleetManagement.sln --no-restore --configuration Release

      - name: Run all tests with coverage
        run: |
          dotnet test MotoFleetManagement.sln --no-build --configuration Release \
            --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Move Coverage Files to Single Location
        run: |
          mkdir -p ./coverage
          find ./TestResults -name 'coverage.cobertura.xml' -exec cp {} ./coverage/ \;

      - name: Combine Coverage Files
        run: |
          dotnet tool install --global coverlet.console || echo "Coverlet already installed"
          coverlet ./coverage/ --merge-with ./coverage/coverage.cobertura.xml \
            -o ./coverage/combined.cobertura.xml

      - name: Debug Coverage Files
        run: |
          echo "Here is the structure of ./coverage:"
          ls -l ./coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage.cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-coverage-report
          fail_ci_if_error: true
